# Generated by Django 5.0.6 on 2026-04-10 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Business phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Business physical address', null=True)),
                ('description', models.TextField(blank=True, help_text='Business description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the business is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the business was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the business was last updated')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
