# Generated by Django 5.0.6 on 2026-04-10 15:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Service name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently offered')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the service was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the service was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the service was soft deleted', null=True)),
                ('business', models.ForeignKey(help_text='Business this service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'is_deleted'], name='services_busines_d3578f_idx'), models.Index(fields=['business', 'is_active'], name='services_busines_302365_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_service_name_per_business'),
        ),
    ]
