# Generated by Django 5.0.6 on 2026-04-10 15:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Client's full name", max_length=255)),
                ('phone', models.CharField(help_text="Client's phone number", max_length=20)),
                ('email', models.EmailField(blank=True, help_text="Client's email address", max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the client', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the client is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the client was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the client was soft deleted', null=True)),
                ('business', models.ForeignKey(help_text='Business this client belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'is_deleted'], name='clients_busines_77309f_idx'), models.Index(fields=['business', 'is_active'], name='clients_busines_ac836c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('business', 'email'), name='unique_client_email_per_business'),
        ),
    ]
