# Generated by Django 5.0.6 on 2026-04-10 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='Appointment start time')),
                ('end_time', models.DateTimeField(help_text='Appointment end time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', help_text='Current appointment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the appointment', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the appointment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the appointment was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the appointment was soft deleted', null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-start_time'],
            },
        ),
    ]
