# Generated by Django 5.0.6 on 2026-04-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('businesses', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='business',
            field=models.ForeignKey(help_text='Business this appointment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(help_text='Client for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Service being provided', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'start_time'], name='appointment_busines_ba40ec_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'status', 'is_deleted'], name='appointment_busines_fa9d82_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'start_time'], name='appointment_client__63cb01_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
    ]
